#!/usr/bin/env python3
"""Regenerate the GoHighLevel paste files from the source page.

Run from the repo root:  python3 docs/ghl/build-ghl-files.py

public/iron-tribe-bring-a-friend.html is the source of truth. This script scopes
its CSS to #itf-rooted so nothing can leak into GHL's own sections or the builder
chrome, splits the result into one CSS paste and one code-element paste, and
tokenises the six image URLs so they have to be pointed at GHL Media Storage.

Outputs: page-custom-css.css, page-custom-code.html, seo-fields.md
README.md is written by hand and is not touched.
"""
import io, os, re

SRC = 'public/iron-tribe-bring-a-friend.html'
OUT = 'docs/ghl'
W   = '#itf-rooted'

IMG = {
    'hero-kettlebell-class':  'HERO',
    'class-coaching':         'CLASS',
    'detail-kettlebell-rack': 'KETTLEBELL',
    'detail-rower':           'ROWER',
    'band-class-plank':       'BAND',
    'closing-deadlift-pair':  'CLOSING',
}


def chunks(text):
    """Split CSS into (comment | at-rule | rule) tuples, honouring nested braces."""
    i, out = 0, []
    while i < len(text):
        if text[i] in ' \n\t':
            i += 1; continue
        if text.startswith('/*', i):
            j = text.index('*/', i) + 2
            out.append(('comment', text[i:j])); i = j; continue
        if text[i] == '@':
            head_end = text.index('{', i)
            depth, j = 0, head_end
            while True:
                if text[j] == '{': depth += 1
                elif text[j] == '}':
                    depth -= 1
                    if depth == 0: break
                j += 1
            out.append(('at', text[i:head_end], text[head_end + 1:j])); i = j + 1; continue
        b = text.index('{', i); e = text.index('}', b)
        out.append(('rule', text[i:b], text[b + 1:e])); i = e + 1
    return out


def scope_one(sel):
    sel = sel.strip()
    if not sel:
        return sel
    # these three targeted the document itself; the wrapper stands in for them
    if sel in (':root', 'html', 'body'):
        return W
    # `.js` moves onto the wrapper, so it is a compound, not a descendant
    if sel.startswith('.js '):
        return W + '.js ' + sel[4:]
    if sel.startswith(W):
        return sel
    return W + ' ' + sel


def render(items):
    out = []
    for it in items:
        if it[0] == 'comment':
            out.append(it[1])
        elif it[0] == 'at':
            head, inner = it[1].strip(), it[2]
            if head.startswith(('@media', '@supports')):
                out.append(head + '{\n' + render(chunks(inner)) + '\n}')
            else:                     # @font-face, @keyframes: no selectors to scope
                out.append(head + '{' + inner + '}')
        else:
            out.append(','.join(scope_one(p) for p in it[1].split(',')) + '{' + it[2] + '}')
    return '\n'.join(out)


def meta(src, pattern):
    m = re.search(pattern, src)
    return m.group(1) if m else '(not found)'


def main():
    src = io.open(SRC, encoding='utf-8').read()
    css = src[src.index('<style>') + 7:src.index('</style>')]
    body = src[src.index('<body>') + 6:src.index('</body>')]
    scripts = re.findall(r'<script>(.*?)</script>', src, re.S)

    scoped = render(chunks(css))
    leaks = re.findall(r'(?m)^(html|body|\*|:root)\s*[,{]', scoped)
    assert not leaks, 'unscoped rules would leak into GHL: %s' % leaks

    out_css = """/* ============================================================================
   Iron Tribe "Rooted" landing page - PAGE CUSTOM CSS
   Paste this whole file into: Page Settings -> Custom CSS
   ----------------------------------------------------------------------------
   GENERATED by docs/ghl/build-ghl-files.py from
   public/iron-tribe-bring-a-friend.html. Do not hand edit; regenerate.

   Everything below the GLOBAL block is scoped to #itf-rooted so it cannot leak
   into GHL's own sections, the builder chrome, or any other element on the page.
   Do not remove the #itf-rooted prefixes.
   ========================================================================= */

/* ---- GLOBAL: the only three things that must live outside the block ---- */
/* @import has to stay the first rule in the file or CSS discards it. */
@import url('https://fonts.googleapis.com/css2?family=Archivo:wght@600;700;800;900&family=Barlow+Semi+Condensed:wght@500;600;700&family=Mulish:wght@400;500;600;700&display=swap');

html{scroll-behavior:smooth;scroll-padding-top:70px}  /* anchor nav + sticky header offset */
body{background:#000}                                  /* no white gap above or below the block */

/* ---- SCOPED: the page itself ---- */
""" + scoped + "\n"

    for name, tok in IMG.items():
        body = body.replace('/img/rooted/%s.jpg' % name, 'REPLACE_%s_URL' % tok)

    js = '\n'.join(x.strip() for x in scripts if 'documentElement' not in x)
    out_html = """<!-- ============================================================================
     Iron Tribe "Rooted" landing page - CUSTOM CODE ELEMENT
     Paste this whole file into a Custom JS/HTML element on the page.
     The matching CSS goes in Page Settings -> Custom CSS (page-custom-css.css).

     GENERATED by docs/ghl/build-ghl-files.py. Do not hand edit; regenerate.

     BEFORE IT WILL WORK you must replace SIX image URLs and TWO config values.
     Search this file for REPLACE_ and for NEEDS INPUT.
     ========================================================================= -->
<div id="itf-rooted">
""" + body.strip() + """
<script>
/* the .js hook goes on the wrapper, not <html>, so the scoped CSS matches */
document.getElementById('itf-rooted').classList.add('js');
""" + js + """
</script>
</div>
"""

    out_seo = """# SEO and social fields for the GHL page

GENERATED by `docs/ghl/build-ghl-files.py`. Do not hand edit; regenerate.

Copy these into Builder -> Settings -> SEO Meta Data.

## Page title
%s

## Meta description
%s

## Open Graph title
%s

## Open Graph description
%s

## Share image
Upload `public/og-bring-a-friend.jpg` (1200x630) to GHL Media Storage and paste its
**full absolute URL** here. A root-relative path will not resolve on Facebook or
LinkedIn.

Alt text: %s

## Twitter
Card type: summary_large_image
Title: same as the Open Graph title
Description:
%s
""" % (
        meta(src, r'<title>(.*?)</title>'),
        meta(src, r'<meta name="description" content="(.*?)"'),
        meta(src, r'<meta property="og:title" content="(.*?)"'),
        meta(src, r'<meta property="og:description" content="(.*?)"'),
        meta(src, r'<meta property="og:image:alt" content="(.*?)"'),
        meta(src, r'<meta name="twitter:description" content="(.*?)"'),
    )

    os.makedirs(OUT, exist_ok=True)
    io.open(OUT + '/page-custom-css.css', 'w', encoding='utf-8').write(out_css)
    io.open(OUT + '/page-custom-code.html', 'w', encoding='utf-8').write(out_html)
    io.open(OUT + '/seo-fields.md', 'w', encoding='utf-8').write(out_seo)

    assert len(re.findall(r'REPLACE_\w+_URL', out_html)) == len(IMG)
    print('page-custom-css.css   %6d bytes' % len(out_css))
    print('page-custom-code.html %6d bytes' % len(out_html))
    print('seo-fields.md         %6d bytes' % len(out_seo))
    print('image tokens: %d   unscoped leaks: 0' % len(IMG))


if __name__ == '__main__':
    main()
